---
driver:
  name: vagrant
  vm_hostname: 'kong.local'
  # without additional memory, ubuntu suites will fail
  customize:
    memory: 1024
  network:
  - ["forwarded_port", {guest: 8000, host: 8000, auto_correct: true}]
  - ["forwarded_port", {guest: 8001, host: 8001, auto_correct: true}]
  - ["forwarded_port", {guest: 8443, host: 8443, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: centos-6.7
- name: centos-7.2
- name: debian-6.0.10
  run_list: recipe[apt]
- name: debian-7.9
  run_list: recipe[apt]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-15.04
  run_list: recipe[apt]

suites:
- name: default
  run_list:
  - recipe[kong_test]
- name: postgresql
  run_list:
    - recipe[kong_test]
  attributes:
    kong:
      kong.yml:
        database: postgres
      manage_postgres: true
      manage_cassandra: false
